// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	MailerLogs string
	Profiles   string
	Roles      string
	Users      string
}{
	MailerLogs: "mailer_logs",
	Profiles:   "profiles",
	Roles:      "roles",
	Users:      "users",
}
