// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testMailerLogs(t *testing.T) {
	t.Parallel()

	query := MailerLogs()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testMailerLogsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MailerLog{}
	if err = randomize.Struct(seed, o, mailerLogDBTypes, true, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MailerLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMailerLogsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MailerLog{}
	if err = randomize.Struct(seed, o, mailerLogDBTypes, true, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := MailerLogs().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MailerLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMailerLogsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MailerLog{}
	if err = randomize.Struct(seed, o, mailerLogDBTypes, true, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MailerLogSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := MailerLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testMailerLogsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MailerLog{}
	if err = randomize.Struct(seed, o, mailerLogDBTypes, true, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := MailerLogExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if MailerLog exists: %s", err)
	}
	if !e {
		t.Errorf("Expected MailerLogExists to return true, but got false.")
	}
}

func testMailerLogsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MailerLog{}
	if err = randomize.Struct(seed, o, mailerLogDBTypes, true, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	mailerLogFound, err := FindMailerLog(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if mailerLogFound == nil {
		t.Error("want a record, got nil")
	}
}

func testMailerLogsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MailerLog{}
	if err = randomize.Struct(seed, o, mailerLogDBTypes, true, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = MailerLogs().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testMailerLogsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MailerLog{}
	if err = randomize.Struct(seed, o, mailerLogDBTypes, true, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := MailerLogs().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testMailerLogsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	mailerLogOne := &MailerLog{}
	mailerLogTwo := &MailerLog{}
	if err = randomize.Struct(seed, mailerLogOne, mailerLogDBTypes, false, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}
	if err = randomize.Struct(seed, mailerLogTwo, mailerLogDBTypes, false, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = mailerLogOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = mailerLogTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MailerLogs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testMailerLogsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	mailerLogOne := &MailerLog{}
	mailerLogTwo := &MailerLog{}
	if err = randomize.Struct(seed, mailerLogOne, mailerLogDBTypes, false, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}
	if err = randomize.Struct(seed, mailerLogTwo, mailerLogDBTypes, false, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = mailerLogOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = mailerLogTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MailerLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func mailerLogBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *MailerLog) error {
	*o = MailerLog{}
	return nil
}

func mailerLogAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *MailerLog) error {
	*o = MailerLog{}
	return nil
}

func mailerLogAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *MailerLog) error {
	*o = MailerLog{}
	return nil
}

func mailerLogBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MailerLog) error {
	*o = MailerLog{}
	return nil
}

func mailerLogAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *MailerLog) error {
	*o = MailerLog{}
	return nil
}

func mailerLogBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MailerLog) error {
	*o = MailerLog{}
	return nil
}

func mailerLogAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *MailerLog) error {
	*o = MailerLog{}
	return nil
}

func mailerLogBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MailerLog) error {
	*o = MailerLog{}
	return nil
}

func mailerLogAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *MailerLog) error {
	*o = MailerLog{}
	return nil
}

func testMailerLogsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &MailerLog{}
	o := &MailerLog{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, mailerLogDBTypes, false); err != nil {
		t.Errorf("Unable to randomize MailerLog object: %s", err)
	}

	AddMailerLogHook(boil.BeforeInsertHook, mailerLogBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	mailerLogBeforeInsertHooks = []MailerLogHook{}

	AddMailerLogHook(boil.AfterInsertHook, mailerLogAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	mailerLogAfterInsertHooks = []MailerLogHook{}

	AddMailerLogHook(boil.AfterSelectHook, mailerLogAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	mailerLogAfterSelectHooks = []MailerLogHook{}

	AddMailerLogHook(boil.BeforeUpdateHook, mailerLogBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	mailerLogBeforeUpdateHooks = []MailerLogHook{}

	AddMailerLogHook(boil.AfterUpdateHook, mailerLogAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	mailerLogAfterUpdateHooks = []MailerLogHook{}

	AddMailerLogHook(boil.BeforeDeleteHook, mailerLogBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	mailerLogBeforeDeleteHooks = []MailerLogHook{}

	AddMailerLogHook(boil.AfterDeleteHook, mailerLogAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	mailerLogAfterDeleteHooks = []MailerLogHook{}

	AddMailerLogHook(boil.BeforeUpsertHook, mailerLogBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	mailerLogBeforeUpsertHooks = []MailerLogHook{}

	AddMailerLogHook(boil.AfterUpsertHook, mailerLogAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	mailerLogAfterUpsertHooks = []MailerLogHook{}
}

func testMailerLogsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MailerLog{}
	if err = randomize.Struct(seed, o, mailerLogDBTypes, true, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MailerLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMailerLogsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MailerLog{}
	if err = randomize.Struct(seed, o, mailerLogDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(mailerLogColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := MailerLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testMailerLogsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MailerLog{}
	if err = randomize.Struct(seed, o, mailerLogDBTypes, true, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMailerLogsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MailerLog{}
	if err = randomize.Struct(seed, o, mailerLogDBTypes, true, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := MailerLogSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testMailerLogsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &MailerLog{}
	if err = randomize.Struct(seed, o, mailerLogDBTypes, true, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := MailerLogs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	mailerLogDBTypes = map[string]string{`ID`: `integer`, `Type`: `character varying`, `Payload`: `text`, `Status`: `character varying`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                = bytes.MinRead
)

func testMailerLogsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(mailerLogPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(mailerLogAllColumns) == len(mailerLogPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MailerLog{}
	if err = randomize.Struct(seed, o, mailerLogDBTypes, true, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MailerLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, mailerLogDBTypes, true, mailerLogPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testMailerLogsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(mailerLogAllColumns) == len(mailerLogPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &MailerLog{}
	if err = randomize.Struct(seed, o, mailerLogDBTypes, true, mailerLogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := MailerLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, mailerLogDBTypes, true, mailerLogPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(mailerLogAllColumns, mailerLogPrimaryKeyColumns) {
		fields = mailerLogAllColumns
	} else {
		fields = strmangle.SetComplement(
			mailerLogAllColumns,
			mailerLogPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := MailerLogSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testMailerLogsUpsert(t *testing.T) {
	t.Parallel()

	if len(mailerLogAllColumns) == len(mailerLogPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := MailerLog{}
	if err = randomize.Struct(seed, &o, mailerLogDBTypes, true); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MailerLog: %s", err)
	}

	count, err := MailerLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, mailerLogDBTypes, false, mailerLogPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize MailerLog struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert MailerLog: %s", err)
	}

	count, err = MailerLogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
